# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

#  fileSystems."/" =
#    { device = "/dev/disk/by-label/system";
#      fsType = "btrfs";
#      options = [ "subvol=@" "compress=zstd" "noatime" ];
#    };

#  fileSystems."/boot/efi" =
#    { device = "/dev/disk/by-label/UEFI";
#      fsType = "vfat";
#    };

#  fileSystems."/home" =
#    { device = "/dev/disk/by-label/system";
#      fsType = "btrfs";
#      options = [ "subvol=@home" "compress=zstd" ];
#    };

  fileSystems."/mnt/defvol" =
    { device = "/dev/disk/by-label/system";
      fsType = "btrfs";
      options = [ "subvol=/" ];
    };

  swapDevices = [{
    device = "/swap";
    size = 1024;
  }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
